version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.11.0
    - 3.8.3
    - 3.9.0
    - 3.9.1
  - dependency-name: netlify-lambda
    versions:
    - 2.0.3
    - 2.0.4
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: vuetify-loader
    versions:
    - 1.7.1
  - dependency-name: "@vue/cli-plugin-eslint"
    versions:
    - 4.5.11
